HELLO SOMETHING COMPUTER
ADDED BY JRJRWEBSITE32
<?php
echo "WORD<br>";
echo "LATEST CHANGE - DONE BY JR2 HERE";
echo "PUT HERE BY JR3";
echo "JR2 FIX JR2 AGAIN";
echo "TESTINGAGAIN ANOTHER ADD BY WEBSITE LINE JR2";
BY WEBSITE
echo "FIXED JR2NJR2OPE BY WEBSITE";
echo "EVERYWEB JRSITE2 LATEST";
//WEBSITE
echo "I UPDATED THIS USING JR3 JR2";
if (edit = bywebsite) {
echo "I UPDATED THIS USING JR3";
}
// another update here by James
?>
