HELLO COMPUTER
ADDED BY JR2
<?php
echo "WORD<br>";
echo "LATEST CHANGE - DONE BY JR2 HERE";
echo "PUT HERE BY JR3";
echo "JR2 FIX JR2 AGAIN";
echo "TESTINGAGAIN ANOTHER ADD BY JR2";
echo "FIXED NOPE BY WEBSITE";
echo "EVERY JR2 LATEST";
echo "I UPDATED THIS USING JR3";
// another update here by James
?>
