HELLO COMPUTER
ADDED BY JRJR32
<?php
echo "WORD<br>";
echo "LATEST CHANGE - DONE BY JR2 HERE";
echo "PUT HERE BY JR3";
echo "JR2 FIX JR2 AGAIN";
echo "TESTINGAGAIN ANOTHER ADD BY JR2";
echo "FIXED JR2NJR2OPE BY WEBSITE";
echo "EVERY JR2 LATEST";
echo "I UPDATED THIS USING JR3 JR2";
// another update here by James
?>
